[package]
name = "roast"
version = "0.1.0"
authors = ["Arc-blroth <45273859+Arc-blroth@users.noreply.github.com>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
egui = "0.12.0"
egui_vulkano = { git = "https://github.com/Arc-blroth/egui_vulkano", rev = "ae95a4b" }
glam = { version = "0.15.2" }
image = "0.23.14"
jni = "0.19.0"
lazy_static = "1.4.0"
log = {version = "0.4.14", features = ["std"]}
vulkano = "0.23.0"
vulkano-win = "0.23.0"
vulkano-shaders = "0.23.0"
winit = "0.24.0"
