[workspace]
members = [
    "bosstroves-revenge"
]

# https://github.com/rust-lang/cargo/issues/9996
resolver = "2"

# optimize every package except ours
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
strip = true
opt-level = 3
codegen-units = 1
