#!/bin/sh

# ============================
#     git pre-commit hook
# ============================
# Add this file to .git/hooks/
# to get automatic formatting
# on every commit.

# rustfmt
cargo fmt
git update-index --again
